name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.2"

      - name: Get dependencies
        working-directory: ./services
        run: go mod tidy

      - name: Build library
        working-directory: ./services
        run: go build ./library/cmd/service/main.go

      - name: Build rating
        working-directory: ./services
        run: go build ./rating/cmd/service/main.go

      - name: Build reservation
        working-directory: ./services
        run: go build ./reservation/cmd/service/main.go

      - name: Build gateway
        working-directory: ./services
        run: go build ./gateway/cmd/service/main.go

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.2"

      - name: Get dependencies
        working-directory: ./services
        run: go mod tidy

      - name: Test all
        working-directory: ./services
        run: go test -cover ./...

  autograding:
    name: Autograding
    needs: [ "build", "test" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - name: Build images
        timeout-minutes: 10
        run: docker compose build

      - name: Run containers
        timeout-minutes: 5
        run: |
          docker compose up -d
          ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050

      - name: Run API Tests
        timeout-minutes: 5
        run: ./scripts/test-script.sh
        env:
          VARIANT: v4
          SERVICE_NAME: rating
          PORT_NUMBER: 8050

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v